(cl:defpackage serial_communication-msg
  (:use )
  (:export
   "<CONTROLER_MESSAGE>"
   "CONTROLER_MESSAGE"
   "<FINGER_EGAIN>"
   "FINGER_EGAIN"
   "<FINGER_FORCE>"
   "FINGER_FORCE"
   "<FINGER_IMU>"
   "FINGER_IMU"
   "<FINGER_PRESSURE>"
   "FINGER_PRESSURE"
   "<FINGERPOSE>"
   "FINGERPOSE"
   "<HAND_EGAIN>"
   "HAND_EGAIN"
   "<HAND_FORCE>"
   "HAND_FORCE"
   "<HAND_IMU>"
   "HAND_IMU"
   "<HAND_PRESSURE>"
   "HAND_PRESSURE"
   "<HANDPOSE>"
   "HANDPOSE"
   "<IMU_DATA>"
   "IMU_DATA"
   "<LZQ>"
   "LZQ"
   "<PULSO_MESSAGE>"
   "PULSO_MESSAGE"
   "<SMC_MESSAGE>"
   "SMC_MESSAGE"
  ))

