# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from serial_communication/fingerpose.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class fingerpose(genpy.Message):
  _md5sum = "6052868b9a4add2e7c42afe8a4c83c4d"
  _type = "serial_communication/fingerpose"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Quaternion origin_Q_tag1
geometry_msgs/Quaternion origin_Q_tag2
geometry_msgs/Quaternion origin_Q_tag3
geometry_msgs/Vector3 YAW_DIP
geometry_msgs/Vector3 TRANS_DIP
geometry_msgs/Vector3 YAW_PIP
geometry_msgs/Vector3 TRANS_PIP
geometry_msgs/Vector3 YAW_MCP
geometry_msgs/Vector3 TRANS_MCP

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['origin_Q_tag1','origin_Q_tag2','origin_Q_tag3','YAW_DIP','TRANS_DIP','YAW_PIP','TRANS_PIP','YAW_MCP','TRANS_MCP']
  _slot_types = ['geometry_msgs/Quaternion','geometry_msgs/Quaternion','geometry_msgs/Quaternion','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       origin_Q_tag1,origin_Q_tag2,origin_Q_tag3,YAW_DIP,TRANS_DIP,YAW_PIP,TRANS_PIP,YAW_MCP,TRANS_MCP

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(fingerpose, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.origin_Q_tag1 is None:
        self.origin_Q_tag1 = geometry_msgs.msg.Quaternion()
      if self.origin_Q_tag2 is None:
        self.origin_Q_tag2 = geometry_msgs.msg.Quaternion()
      if self.origin_Q_tag3 is None:
        self.origin_Q_tag3 = geometry_msgs.msg.Quaternion()
      if self.YAW_DIP is None:
        self.YAW_DIP = geometry_msgs.msg.Vector3()
      if self.TRANS_DIP is None:
        self.TRANS_DIP = geometry_msgs.msg.Vector3()
      if self.YAW_PIP is None:
        self.YAW_PIP = geometry_msgs.msg.Vector3()
      if self.TRANS_PIP is None:
        self.TRANS_PIP = geometry_msgs.msg.Vector3()
      if self.YAW_MCP is None:
        self.YAW_MCP = geometry_msgs.msg.Vector3()
      if self.TRANS_MCP is None:
        self.TRANS_MCP = geometry_msgs.msg.Vector3()
    else:
      self.origin_Q_tag1 = geometry_msgs.msg.Quaternion()
      self.origin_Q_tag2 = geometry_msgs.msg.Quaternion()
      self.origin_Q_tag3 = geometry_msgs.msg.Quaternion()
      self.YAW_DIP = geometry_msgs.msg.Vector3()
      self.TRANS_DIP = geometry_msgs.msg.Vector3()
      self.YAW_PIP = geometry_msgs.msg.Vector3()
      self.TRANS_PIP = geometry_msgs.msg.Vector3()
      self.YAW_MCP = geometry_msgs.msg.Vector3()
      self.TRANS_MCP = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_30d().pack(_x.origin_Q_tag1.x, _x.origin_Q_tag1.y, _x.origin_Q_tag1.z, _x.origin_Q_tag1.w, _x.origin_Q_tag2.x, _x.origin_Q_tag2.y, _x.origin_Q_tag2.z, _x.origin_Q_tag2.w, _x.origin_Q_tag3.x, _x.origin_Q_tag3.y, _x.origin_Q_tag3.z, _x.origin_Q_tag3.w, _x.YAW_DIP.x, _x.YAW_DIP.y, _x.YAW_DIP.z, _x.TRANS_DIP.x, _x.TRANS_DIP.y, _x.TRANS_DIP.z, _x.YAW_PIP.x, _x.YAW_PIP.y, _x.YAW_PIP.z, _x.TRANS_PIP.x, _x.TRANS_PIP.y, _x.TRANS_PIP.z, _x.YAW_MCP.x, _x.YAW_MCP.y, _x.YAW_MCP.z, _x.TRANS_MCP.x, _x.TRANS_MCP.y, _x.TRANS_MCP.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.origin_Q_tag1 is None:
        self.origin_Q_tag1 = geometry_msgs.msg.Quaternion()
      if self.origin_Q_tag2 is None:
        self.origin_Q_tag2 = geometry_msgs.msg.Quaternion()
      if self.origin_Q_tag3 is None:
        self.origin_Q_tag3 = geometry_msgs.msg.Quaternion()
      if self.YAW_DIP is None:
        self.YAW_DIP = geometry_msgs.msg.Vector3()
      if self.TRANS_DIP is None:
        self.TRANS_DIP = geometry_msgs.msg.Vector3()
      if self.YAW_PIP is None:
        self.YAW_PIP = geometry_msgs.msg.Vector3()
      if self.TRANS_PIP is None:
        self.TRANS_PIP = geometry_msgs.msg.Vector3()
      if self.YAW_MCP is None:
        self.YAW_MCP = geometry_msgs.msg.Vector3()
      if self.TRANS_MCP is None:
        self.TRANS_MCP = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 240
      (_x.origin_Q_tag1.x, _x.origin_Q_tag1.y, _x.origin_Q_tag1.z, _x.origin_Q_tag1.w, _x.origin_Q_tag2.x, _x.origin_Q_tag2.y, _x.origin_Q_tag2.z, _x.origin_Q_tag2.w, _x.origin_Q_tag3.x, _x.origin_Q_tag3.y, _x.origin_Q_tag3.z, _x.origin_Q_tag3.w, _x.YAW_DIP.x, _x.YAW_DIP.y, _x.YAW_DIP.z, _x.TRANS_DIP.x, _x.TRANS_DIP.y, _x.TRANS_DIP.z, _x.YAW_PIP.x, _x.YAW_PIP.y, _x.YAW_PIP.z, _x.TRANS_PIP.x, _x.TRANS_PIP.y, _x.TRANS_PIP.z, _x.YAW_MCP.x, _x.YAW_MCP.y, _x.YAW_MCP.z, _x.TRANS_MCP.x, _x.TRANS_MCP.y, _x.TRANS_MCP.z,) = _get_struct_30d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_30d().pack(_x.origin_Q_tag1.x, _x.origin_Q_tag1.y, _x.origin_Q_tag1.z, _x.origin_Q_tag1.w, _x.origin_Q_tag2.x, _x.origin_Q_tag2.y, _x.origin_Q_tag2.z, _x.origin_Q_tag2.w, _x.origin_Q_tag3.x, _x.origin_Q_tag3.y, _x.origin_Q_tag3.z, _x.origin_Q_tag3.w, _x.YAW_DIP.x, _x.YAW_DIP.y, _x.YAW_DIP.z, _x.TRANS_DIP.x, _x.TRANS_DIP.y, _x.TRANS_DIP.z, _x.YAW_PIP.x, _x.YAW_PIP.y, _x.YAW_PIP.z, _x.TRANS_PIP.x, _x.TRANS_PIP.y, _x.TRANS_PIP.z, _x.YAW_MCP.x, _x.YAW_MCP.y, _x.YAW_MCP.z, _x.TRANS_MCP.x, _x.TRANS_MCP.y, _x.TRANS_MCP.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.origin_Q_tag1 is None:
        self.origin_Q_tag1 = geometry_msgs.msg.Quaternion()
      if self.origin_Q_tag2 is None:
        self.origin_Q_tag2 = geometry_msgs.msg.Quaternion()
      if self.origin_Q_tag3 is None:
        self.origin_Q_tag3 = geometry_msgs.msg.Quaternion()
      if self.YAW_DIP is None:
        self.YAW_DIP = geometry_msgs.msg.Vector3()
      if self.TRANS_DIP is None:
        self.TRANS_DIP = geometry_msgs.msg.Vector3()
      if self.YAW_PIP is None:
        self.YAW_PIP = geometry_msgs.msg.Vector3()
      if self.TRANS_PIP is None:
        self.TRANS_PIP = geometry_msgs.msg.Vector3()
      if self.YAW_MCP is None:
        self.YAW_MCP = geometry_msgs.msg.Vector3()
      if self.TRANS_MCP is None:
        self.TRANS_MCP = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 240
      (_x.origin_Q_tag1.x, _x.origin_Q_tag1.y, _x.origin_Q_tag1.z, _x.origin_Q_tag1.w, _x.origin_Q_tag2.x, _x.origin_Q_tag2.y, _x.origin_Q_tag2.z, _x.origin_Q_tag2.w, _x.origin_Q_tag3.x, _x.origin_Q_tag3.y, _x.origin_Q_tag3.z, _x.origin_Q_tag3.w, _x.YAW_DIP.x, _x.YAW_DIP.y, _x.YAW_DIP.z, _x.TRANS_DIP.x, _x.TRANS_DIP.y, _x.TRANS_DIP.z, _x.YAW_PIP.x, _x.YAW_PIP.y, _x.YAW_PIP.z, _x.TRANS_PIP.x, _x.TRANS_PIP.y, _x.TRANS_PIP.z, _x.YAW_MCP.x, _x.YAW_MCP.y, _x.YAW_MCP.z, _x.TRANS_MCP.x, _x.TRANS_MCP.y, _x.TRANS_MCP.z,) = _get_struct_30d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_30d = None
def _get_struct_30d():
    global _struct_30d
    if _struct_30d is None:
        _struct_30d = struct.Struct("<30d")
    return _struct_30d
