# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from serial_communication/hand_force.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import serial_communication.msg

class hand_force(genpy.Message):
  _md5sum = "a6cf3f7e3a0f71d7ff44682c65d9ef34"
  _type = "serial_communication/hand_force"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """finger_force THUMB0
finger_force THUMB1
finger_force INDEX
finger_force MIDDLE
finger_force RING
finger_force LITTLE

================================================================================
MSG: serial_communication/finger_force
float32 FORCE1
float32 FORCE2
float32 FORCE3
float32 FORCE4
"""
  __slots__ = ['THUMB0','THUMB1','INDEX','MIDDLE','RING','LITTLE']
  _slot_types = ['serial_communication/finger_force','serial_communication/finger_force','serial_communication/finger_force','serial_communication/finger_force','serial_communication/finger_force','serial_communication/finger_force']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       THUMB0,THUMB1,INDEX,MIDDLE,RING,LITTLE

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(hand_force, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.THUMB0 is None:
        self.THUMB0 = serial_communication.msg.finger_force()
      if self.THUMB1 is None:
        self.THUMB1 = serial_communication.msg.finger_force()
      if self.INDEX is None:
        self.INDEX = serial_communication.msg.finger_force()
      if self.MIDDLE is None:
        self.MIDDLE = serial_communication.msg.finger_force()
      if self.RING is None:
        self.RING = serial_communication.msg.finger_force()
      if self.LITTLE is None:
        self.LITTLE = serial_communication.msg.finger_force()
    else:
      self.THUMB0 = serial_communication.msg.finger_force()
      self.THUMB1 = serial_communication.msg.finger_force()
      self.INDEX = serial_communication.msg.finger_force()
      self.MIDDLE = serial_communication.msg.finger_force()
      self.RING = serial_communication.msg.finger_force()
      self.LITTLE = serial_communication.msg.finger_force()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_24f().pack(_x.THUMB0.FORCE1, _x.THUMB0.FORCE2, _x.THUMB0.FORCE3, _x.THUMB0.FORCE4, _x.THUMB1.FORCE1, _x.THUMB1.FORCE2, _x.THUMB1.FORCE3, _x.THUMB1.FORCE4, _x.INDEX.FORCE1, _x.INDEX.FORCE2, _x.INDEX.FORCE3, _x.INDEX.FORCE4, _x.MIDDLE.FORCE1, _x.MIDDLE.FORCE2, _x.MIDDLE.FORCE3, _x.MIDDLE.FORCE4, _x.RING.FORCE1, _x.RING.FORCE2, _x.RING.FORCE3, _x.RING.FORCE4, _x.LITTLE.FORCE1, _x.LITTLE.FORCE2, _x.LITTLE.FORCE3, _x.LITTLE.FORCE4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.THUMB0 is None:
        self.THUMB0 = serial_communication.msg.finger_force()
      if self.THUMB1 is None:
        self.THUMB1 = serial_communication.msg.finger_force()
      if self.INDEX is None:
        self.INDEX = serial_communication.msg.finger_force()
      if self.MIDDLE is None:
        self.MIDDLE = serial_communication.msg.finger_force()
      if self.RING is None:
        self.RING = serial_communication.msg.finger_force()
      if self.LITTLE is None:
        self.LITTLE = serial_communication.msg.finger_force()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.THUMB0.FORCE1, _x.THUMB0.FORCE2, _x.THUMB0.FORCE3, _x.THUMB0.FORCE4, _x.THUMB1.FORCE1, _x.THUMB1.FORCE2, _x.THUMB1.FORCE3, _x.THUMB1.FORCE4, _x.INDEX.FORCE1, _x.INDEX.FORCE2, _x.INDEX.FORCE3, _x.INDEX.FORCE4, _x.MIDDLE.FORCE1, _x.MIDDLE.FORCE2, _x.MIDDLE.FORCE3, _x.MIDDLE.FORCE4, _x.RING.FORCE1, _x.RING.FORCE2, _x.RING.FORCE3, _x.RING.FORCE4, _x.LITTLE.FORCE1, _x.LITTLE.FORCE2, _x.LITTLE.FORCE3, _x.LITTLE.FORCE4,) = _get_struct_24f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_24f().pack(_x.THUMB0.FORCE1, _x.THUMB0.FORCE2, _x.THUMB0.FORCE3, _x.THUMB0.FORCE4, _x.THUMB1.FORCE1, _x.THUMB1.FORCE2, _x.THUMB1.FORCE3, _x.THUMB1.FORCE4, _x.INDEX.FORCE1, _x.INDEX.FORCE2, _x.INDEX.FORCE3, _x.INDEX.FORCE4, _x.MIDDLE.FORCE1, _x.MIDDLE.FORCE2, _x.MIDDLE.FORCE3, _x.MIDDLE.FORCE4, _x.RING.FORCE1, _x.RING.FORCE2, _x.RING.FORCE3, _x.RING.FORCE4, _x.LITTLE.FORCE1, _x.LITTLE.FORCE2, _x.LITTLE.FORCE3, _x.LITTLE.FORCE4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.THUMB0 is None:
        self.THUMB0 = serial_communication.msg.finger_force()
      if self.THUMB1 is None:
        self.THUMB1 = serial_communication.msg.finger_force()
      if self.INDEX is None:
        self.INDEX = serial_communication.msg.finger_force()
      if self.MIDDLE is None:
        self.MIDDLE = serial_communication.msg.finger_force()
      if self.RING is None:
        self.RING = serial_communication.msg.finger_force()
      if self.LITTLE is None:
        self.LITTLE = serial_communication.msg.finger_force()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.THUMB0.FORCE1, _x.THUMB0.FORCE2, _x.THUMB0.FORCE3, _x.THUMB0.FORCE4, _x.THUMB1.FORCE1, _x.THUMB1.FORCE2, _x.THUMB1.FORCE3, _x.THUMB1.FORCE4, _x.INDEX.FORCE1, _x.INDEX.FORCE2, _x.INDEX.FORCE3, _x.INDEX.FORCE4, _x.MIDDLE.FORCE1, _x.MIDDLE.FORCE2, _x.MIDDLE.FORCE3, _x.MIDDLE.FORCE4, _x.RING.FORCE1, _x.RING.FORCE2, _x.RING.FORCE3, _x.RING.FORCE4, _x.LITTLE.FORCE1, _x.LITTLE.FORCE2, _x.LITTLE.FORCE3, _x.LITTLE.FORCE4,) = _get_struct_24f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_24f = None
def _get_struct_24f():
    global _struct_24f
    if _struct_24f is None:
        _struct_24f = struct.Struct("<24f")
    return _struct_24f
