# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from serial_communication/pulso_message.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class pulso_message(genpy.Message):
  _md5sum = "93fb5a6b0af4819896193f51aafdbf6d"
  _type = "serial_communication/pulso_message"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 ID
uint16 static_pressure_1
uint16 static_pressure_2
uint16 static_pressure_3
uint16 dynamic_pulse_1
uint16 dynamic_pulse_2
uint16 dynamic_pulse_3
"""
  __slots__ = ['ID','static_pressure_1','static_pressure_2','static_pressure_3','dynamic_pulse_1','dynamic_pulse_2','dynamic_pulse_3']
  _slot_types = ['uint8','uint16','uint16','uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ID,static_pressure_1,static_pressure_2,static_pressure_3,dynamic_pulse_1,dynamic_pulse_2,dynamic_pulse_3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pulso_message, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ID is None:
        self.ID = 0
      if self.static_pressure_1 is None:
        self.static_pressure_1 = 0
      if self.static_pressure_2 is None:
        self.static_pressure_2 = 0
      if self.static_pressure_3 is None:
        self.static_pressure_3 = 0
      if self.dynamic_pulse_1 is None:
        self.dynamic_pulse_1 = 0
      if self.dynamic_pulse_2 is None:
        self.dynamic_pulse_2 = 0
      if self.dynamic_pulse_3 is None:
        self.dynamic_pulse_3 = 0
    else:
      self.ID = 0
      self.static_pressure_1 = 0
      self.static_pressure_2 = 0
      self.static_pressure_3 = 0
      self.dynamic_pulse_1 = 0
      self.dynamic_pulse_2 = 0
      self.dynamic_pulse_3 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B6H().pack(_x.ID, _x.static_pressure_1, _x.static_pressure_2, _x.static_pressure_3, _x.dynamic_pulse_1, _x.dynamic_pulse_2, _x.dynamic_pulse_3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.ID, _x.static_pressure_1, _x.static_pressure_2, _x.static_pressure_3, _x.dynamic_pulse_1, _x.dynamic_pulse_2, _x.dynamic_pulse_3,) = _get_struct_B6H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B6H().pack(_x.ID, _x.static_pressure_1, _x.static_pressure_2, _x.static_pressure_3, _x.dynamic_pulse_1, _x.dynamic_pulse_2, _x.dynamic_pulse_3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.ID, _x.static_pressure_1, _x.static_pressure_2, _x.static_pressure_3, _x.dynamic_pulse_1, _x.dynamic_pulse_2, _x.dynamic_pulse_3,) = _get_struct_B6H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B6H = None
def _get_struct_B6H():
    global _struct_B6H
    if _struct_B6H is None:
        _struct_B6H = struct.Struct("<B6H")
    return _struct_B6H
