# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from serial_communication/smc_message.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class smc_message(genpy.Message):
  _md5sum = "bf432afdc339653f15d6954de7920050"
  _type = "serial_communication/smc_message"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 ID
uint32 time
float32 target_pressure
float32 feedback_pressure
float32 error
float32 smc_uc
int32 valve_mode
"""
  __slots__ = ['ID','time','target_pressure','feedback_pressure','error','smc_uc','valve_mode']
  _slot_types = ['uint8','uint32','float32','float32','float32','float32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ID,time,target_pressure,feedback_pressure,error,smc_uc,valve_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(smc_message, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ID is None:
        self.ID = 0
      if self.time is None:
        self.time = 0
      if self.target_pressure is None:
        self.target_pressure = 0.
      if self.feedback_pressure is None:
        self.feedback_pressure = 0.
      if self.error is None:
        self.error = 0.
      if self.smc_uc is None:
        self.smc_uc = 0.
      if self.valve_mode is None:
        self.valve_mode = 0
    else:
      self.ID = 0
      self.time = 0
      self.target_pressure = 0.
      self.feedback_pressure = 0.
      self.error = 0.
      self.smc_uc = 0.
      self.valve_mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BI4fi().pack(_x.ID, _x.time, _x.target_pressure, _x.feedback_pressure, _x.error, _x.smc_uc, _x.valve_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.ID, _x.time, _x.target_pressure, _x.feedback_pressure, _x.error, _x.smc_uc, _x.valve_mode,) = _get_struct_BI4fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BI4fi().pack(_x.ID, _x.time, _x.target_pressure, _x.feedback_pressure, _x.error, _x.smc_uc, _x.valve_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.ID, _x.time, _x.target_pressure, _x.feedback_pressure, _x.error, _x.smc_uc, _x.valve_mode,) = _get_struct_BI4fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BI4fi = None
def _get_struct_BI4fi():
    global _struct_BI4fi
    if _struct_BI4fi is None:
        _struct_BI4fi = struct.Struct("<BI4fi")
    return _struct_BI4fi
