// Generated by gencpp from file serial_communication/handpose.msg
// DO NOT EDIT!


#ifndef SERIAL_COMMUNICATION_MESSAGE_HANDPOSE_H
#define SERIAL_COMMUNICATION_MESSAGE_HANDPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <serial_communication/fingerpose.h>
#include <serial_communication/fingerpose.h>
#include <serial_communication/fingerpose.h>
#include <serial_communication/fingerpose.h>
#include <serial_communication/fingerpose.h>

namespace serial_communication
{
template <class ContainerAllocator>
struct handpose_
{
  typedef handpose_<ContainerAllocator> Type;

  handpose_()
    : THUMB()
    , INDEX()
    , MIDDLE()
    , RING()
    , LITTLE()  {
    }
  handpose_(const ContainerAllocator& _alloc)
    : THUMB(_alloc)
    , INDEX(_alloc)
    , MIDDLE(_alloc)
    , RING(_alloc)
    , LITTLE(_alloc)  {
  (void)_alloc;
    }



   typedef  ::serial_communication::fingerpose_<ContainerAllocator>  _THUMB_type;
  _THUMB_type THUMB;

   typedef  ::serial_communication::fingerpose_<ContainerAllocator>  _INDEX_type;
  _INDEX_type INDEX;

   typedef  ::serial_communication::fingerpose_<ContainerAllocator>  _MIDDLE_type;
  _MIDDLE_type MIDDLE;

   typedef  ::serial_communication::fingerpose_<ContainerAllocator>  _RING_type;
  _RING_type RING;

   typedef  ::serial_communication::fingerpose_<ContainerAllocator>  _LITTLE_type;
  _LITTLE_type LITTLE;





  typedef boost::shared_ptr< ::serial_communication::handpose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_communication::handpose_<ContainerAllocator> const> ConstPtr;

}; // struct handpose_

typedef ::serial_communication::handpose_<std::allocator<void> > handpose;

typedef boost::shared_ptr< ::serial_communication::handpose > handposePtr;
typedef boost::shared_ptr< ::serial_communication::handpose const> handposeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_communication::handpose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_communication::handpose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_communication::handpose_<ContainerAllocator1> & lhs, const ::serial_communication::handpose_<ContainerAllocator2> & rhs)
{
  return lhs.THUMB == rhs.THUMB &&
    lhs.INDEX == rhs.INDEX &&
    lhs.MIDDLE == rhs.MIDDLE &&
    lhs.RING == rhs.RING &&
    lhs.LITTLE == rhs.LITTLE;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_communication::handpose_<ContainerAllocator1> & lhs, const ::serial_communication::handpose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serial_communication::handpose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_communication::handpose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_communication::handpose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_communication::handpose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_communication::handpose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_communication::handpose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_communication::handpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "130a0e6ad943d5ddee12bd6504eebd8e";
  }

  static const char* value(const ::serial_communication::handpose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x130a0e6ad943d5ddULL;
  static const uint64_t static_value2 = 0xee12bd6504eebd8eULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_communication::handpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_communication/handpose";
  }

  static const char* value(const ::serial_communication::handpose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_communication::handpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fingerpose THUMB\n"
"fingerpose INDEX\n"
"fingerpose MIDDLE\n"
"fingerpose RING\n"
"fingerpose LITTLE\n"
"================================================================================\n"
"MSG: serial_communication/fingerpose\n"
"geometry_msgs/Quaternion origin_Q_tag1\n"
"geometry_msgs/Quaternion origin_Q_tag2\n"
"geometry_msgs/Quaternion origin_Q_tag3\n"
"geometry_msgs/Vector3 YAW_DIP\n"
"geometry_msgs/Vector3 TRANS_DIP\n"
"geometry_msgs/Vector3 YAW_PIP\n"
"geometry_msgs/Vector3 TRANS_PIP\n"
"geometry_msgs/Vector3 YAW_MCP\n"
"geometry_msgs/Vector3 TRANS_MCP\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::serial_communication::handpose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_communication::handpose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.THUMB);
      stream.next(m.INDEX);
      stream.next(m.MIDDLE);
      stream.next(m.RING);
      stream.next(m.LITTLE);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct handpose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_communication::handpose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_communication::handpose_<ContainerAllocator>& v)
  {
    s << indent << "THUMB: ";
    s << std::endl;
    Printer< ::serial_communication::fingerpose_<ContainerAllocator> >::stream(s, indent + "  ", v.THUMB);
    s << indent << "INDEX: ";
    s << std::endl;
    Printer< ::serial_communication::fingerpose_<ContainerAllocator> >::stream(s, indent + "  ", v.INDEX);
    s << indent << "MIDDLE: ";
    s << std::endl;
    Printer< ::serial_communication::fingerpose_<ContainerAllocator> >::stream(s, indent + "  ", v.MIDDLE);
    s << indent << "RING: ";
    s << std::endl;
    Printer< ::serial_communication::fingerpose_<ContainerAllocator> >::stream(s, indent + "  ", v.RING);
    s << indent << "LITTLE: ";
    s << std::endl;
    Printer< ::serial_communication::fingerpose_<ContainerAllocator> >::stream(s, indent + "  ", v.LITTLE);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_COMMUNICATION_MESSAGE_HANDPOSE_H
