// Generated by gencpp from file serial_communication/hand_imu.msg
// DO NOT EDIT!


#ifndef SERIAL_COMMUNICATION_MESSAGE_HAND_IMU_H
#define SERIAL_COMMUNICATION_MESSAGE_HAND_IMU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <serial_communication/finger_imu.h>
#include <serial_communication/finger_imu.h>
#include <serial_communication/finger_imu.h>
#include <serial_communication/finger_imu.h>
#include <serial_communication/finger_imu.h>
#include <serial_communication/imu_data.h>

namespace serial_communication
{
template <class ContainerAllocator>
struct hand_imu_
{
  typedef hand_imu_<ContainerAllocator> Type;

  hand_imu_()
    : ID(0)
    , time(0)
    , THUMB()
    , INDEX()
    , MIDDLE()
    , RING()
    , LITTLE()
    , PALM()  {
    }
  hand_imu_(const ContainerAllocator& _alloc)
    : ID(0)
    , time(0)
    , THUMB(_alloc)
    , INDEX(_alloc)
    , MIDDLE(_alloc)
    , RING(_alloc)
    , LITTLE(_alloc)
    , PALM(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _ID_type;
  _ID_type ID;

   typedef uint16_t _time_type;
  _time_type time;

   typedef  ::serial_communication::finger_imu_<ContainerAllocator>  _THUMB_type;
  _THUMB_type THUMB;

   typedef  ::serial_communication::finger_imu_<ContainerAllocator>  _INDEX_type;
  _INDEX_type INDEX;

   typedef  ::serial_communication::finger_imu_<ContainerAllocator>  _MIDDLE_type;
  _MIDDLE_type MIDDLE;

   typedef  ::serial_communication::finger_imu_<ContainerAllocator>  _RING_type;
  _RING_type RING;

   typedef  ::serial_communication::finger_imu_<ContainerAllocator>  _LITTLE_type;
  _LITTLE_type LITTLE;

   typedef  ::serial_communication::imu_data_<ContainerAllocator>  _PALM_type;
  _PALM_type PALM;





  typedef boost::shared_ptr< ::serial_communication::hand_imu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_communication::hand_imu_<ContainerAllocator> const> ConstPtr;

}; // struct hand_imu_

typedef ::serial_communication::hand_imu_<std::allocator<void> > hand_imu;

typedef boost::shared_ptr< ::serial_communication::hand_imu > hand_imuPtr;
typedef boost::shared_ptr< ::serial_communication::hand_imu const> hand_imuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_communication::hand_imu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_communication::hand_imu_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_communication::hand_imu_<ContainerAllocator1> & lhs, const ::serial_communication::hand_imu_<ContainerAllocator2> & rhs)
{
  return lhs.ID == rhs.ID &&
    lhs.time == rhs.time &&
    lhs.THUMB == rhs.THUMB &&
    lhs.INDEX == rhs.INDEX &&
    lhs.MIDDLE == rhs.MIDDLE &&
    lhs.RING == rhs.RING &&
    lhs.LITTLE == rhs.LITTLE &&
    lhs.PALM == rhs.PALM;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_communication::hand_imu_<ContainerAllocator1> & lhs, const ::serial_communication::hand_imu_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serial_communication::hand_imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_communication::hand_imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_communication::hand_imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_communication::hand_imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_communication::hand_imu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_communication::hand_imu_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_communication::hand_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea982f9506f64da059eb7d3969f058f4";
  }

  static const char* value(const ::serial_communication::hand_imu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea982f9506f64da0ULL;
  static const uint64_t static_value2 = 0x59eb7d3969f058f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_communication::hand_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_communication/hand_imu";
  }

  static const char* value(const ::serial_communication::hand_imu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_communication::hand_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ID\n"
"uint16 time\n"
"finger_imu THUMB\n"
"finger_imu INDEX\n"
"finger_imu MIDDLE\n"
"finger_imu RING\n"
"finger_imu LITTLE\n"
"imu_data PALM\n"
"================================================================================\n"
"MSG: serial_communication/finger_imu\n"
"imu_data PIP\n"
"imu_data DIP\n"
"imu_data MCP\n"
"================================================================================\n"
"MSG: serial_communication/imu_data\n"
"float32 q0\n"
"float32 q1\n"
"float32 q2\n"
"float32 q3\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::serial_communication::hand_imu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_communication::hand_imu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.time);
      stream.next(m.THUMB);
      stream.next(m.INDEX);
      stream.next(m.MIDDLE);
      stream.next(m.RING);
      stream.next(m.LITTLE);
      stream.next(m.PALM);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hand_imu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_communication::hand_imu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_communication::hand_imu_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ID);
    s << indent << "time: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.time);
    s << indent << "THUMB: ";
    s << std::endl;
    Printer< ::serial_communication::finger_imu_<ContainerAllocator> >::stream(s, indent + "  ", v.THUMB);
    s << indent << "INDEX: ";
    s << std::endl;
    Printer< ::serial_communication::finger_imu_<ContainerAllocator> >::stream(s, indent + "  ", v.INDEX);
    s << indent << "MIDDLE: ";
    s << std::endl;
    Printer< ::serial_communication::finger_imu_<ContainerAllocator> >::stream(s, indent + "  ", v.MIDDLE);
    s << indent << "RING: ";
    s << std::endl;
    Printer< ::serial_communication::finger_imu_<ContainerAllocator> >::stream(s, indent + "  ", v.RING);
    s << indent << "LITTLE: ";
    s << std::endl;
    Printer< ::serial_communication::finger_imu_<ContainerAllocator> >::stream(s, indent + "  ", v.LITTLE);
    s << indent << "PALM: ";
    s << std::endl;
    Printer< ::serial_communication::imu_data_<ContainerAllocator> >::stream(s, indent + "  ", v.PALM);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_COMMUNICATION_MESSAGE_HAND_IMU_H
