# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nano_17_ethercat/FT_nano17.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FT_nano17(genpy.Message):
  _md5sum = "b3cc10406904387a2b764bbc39a449c3"
  _type = "nano_17_ethercat/FT_nano17"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 TORQUE_X
float32 TORQUE_Y
float32 TORQUE_Z
float32 FORCE_X
float32 FORCE_Y
float32 FORCE_Z
"""
  __slots__ = ['TORQUE_X','TORQUE_Y','TORQUE_Z','FORCE_X','FORCE_Y','FORCE_Z']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       TORQUE_X,TORQUE_Y,TORQUE_Z,FORCE_X,FORCE_Y,FORCE_Z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FT_nano17, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.TORQUE_X is None:
        self.TORQUE_X = 0.
      if self.TORQUE_Y is None:
        self.TORQUE_Y = 0.
      if self.TORQUE_Z is None:
        self.TORQUE_Z = 0.
      if self.FORCE_X is None:
        self.FORCE_X = 0.
      if self.FORCE_Y is None:
        self.FORCE_Y = 0.
      if self.FORCE_Z is None:
        self.FORCE_Z = 0.
    else:
      self.TORQUE_X = 0.
      self.TORQUE_Y = 0.
      self.TORQUE_Z = 0.
      self.FORCE_X = 0.
      self.FORCE_Y = 0.
      self.FORCE_Z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.TORQUE_X, _x.TORQUE_Y, _x.TORQUE_Z, _x.FORCE_X, _x.FORCE_Y, _x.FORCE_Z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.TORQUE_X, _x.TORQUE_Y, _x.TORQUE_Z, _x.FORCE_X, _x.FORCE_Y, _x.FORCE_Z,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.TORQUE_X, _x.TORQUE_Y, _x.TORQUE_Z, _x.FORCE_X, _x.FORCE_Y, _x.FORCE_Z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.TORQUE_X, _x.TORQUE_Y, _x.TORQUE_Z, _x.FORCE_X, _x.FORCE_Y, _x.FORCE_Z,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
